export interface IRepository {
    "id": number,
    // "node_id": string,
    "name": string,
    "full_name": string,
    "owner": {
        "login": string,
        // "id": number,
        // "node_id": string,
        "avatar_url": string,
    },
    "html_url": string,
    // "description": string,
    // "fork": false,
    // "url": string,
    // "created_at": string,
    // "updated_at": string,
    // "pushed_at": string,
    // "homepage": string,
    // "size": number,
    "stargazers_count": number,
    // "watchers_count": number,
    // "language": string,
    // "forks_count": number,
    // "open_issues_count": number,
    // "master_branch": string,
    // "default_branch": string,
    // "score": number,
    // "archive_url": "https://api.github.com/repos/dtrupenn/Tetris/{archive_format}{/ref}",
    // "assignees_url": "https://api.github.com/repos/dtrupenn/Tetris/assignees{/user}",
    // "blobs_url": "https://api.github.com/repos/dtrupenn/Tetris/git/blobs{/sha}",
    // "branches_url": "https://api.github.com/repos/dtrupenn/Tetris/branches{/branch}",
    // "collaborators_url": "https://api.github.com/repos/dtrupenn/Tetris/collaborators{/collaborator}",
    // "comments_url": "https://api.github.com/repos/dtrupenn/Tetris/comments{/number}",
    // "commits_url": "https://api.github.com/repos/dtrupenn/Tetris/commits{/sha}",
    // "compare_url": "https://api.github.com/repos/dtrupenn/Tetris/compare/{base}...{head}",
    // "contents_url": "https://api.github.com/repos/dtrupenn/Tetris/contents/{+path}",
    // "contributors_url": "https://api.github.com/repos/dtrupenn/Tetris/contributors",
    // "deployments_url": "https://api.github.com/repos/dtrupenn/Tetris/deployments",
    // "downloads_url": "https://api.github.com/repos/dtrupenn/Tetris/downloads",
    // "events_url": "https://api.github.com/repos/dtrupenn/Tetris/events",
    // "forks_url": "https://api.github.com/repos/dtrupenn/Tetris/forks",
    // "git_commits_url": "https://api.github.com/repos/dtrupenn/Tetris/git/commits{/sha}",
    // "git_refs_url": "https://api.github.com/repos/dtrupenn/Tetris/git/refs{/sha}",
    // "git_tags_url": "https://api.github.com/repos/dtrupenn/Tetris/git/tags{/sha}",
    // "git_url": "git:github.com/dtrupenn/Tetris.git",
    // "issue_comment_url": "https://api.github.com/repos/dtrupenn/Tetris/issues/comments{/number}",
    // "issue_events_url": "https://api.github.com/repos/dtrupenn/Tetris/issues/events{/number}",
    // "issues_url": "https://api.github.com/repos/dtrupenn/Tetris/issues{/number}",
    // "keys_url": "https://api.github.com/repos/dtrupenn/Tetris/keys{/key_id}",
    // "labels_url": "https://api.github.com/repos/dtrupenn/Tetris/labels{/name}",
    // "languages_url": "https://api.github.com/repos/dtrupenn/Tetris/languages",
    // "merges_url": "https://api.github.com/repos/dtrupenn/Tetris/merges",
    // "milestones_url": "https://api.github.com/repos/dtrupenn/Tetris/milestones{/number}",
    // "notifications_url": "https://api.github.com/repos/dtrupenn/Tetris/notifications{?since,all,participating}",
    // "pulls_url": "https://api.github.com/repos/dtrupenn/Tetris/pulls{/number}",
    // "releases_url": "https://api.github.com/repos/dtrupenn/Tetris/releases{/id}",
    // "ssh_url": "git@github.com:dtrupenn/Tetris.git",
    // "stargazers_url": "https://api.github.com/repos/dtrupenn/Tetris/stargazers",
    // "statuses_url": "https://api.github.com/repos/dtrupenn/Tetris/statuses/{sha}",
    // "subscribers_url": "https://api.github.com/repos/dtrupenn/Tetris/subscribers",
    // "subscription_url": "https://api.github.com/repos/dtrupenn/Tetris/subscription",
    // "tags_url": "https://api.github.com/repos/dtrupenn/Tetris/tags",
    // "teams_url": "https://api.github.com/repos/dtrupenn/Tetris/teams",
    // "trees_url": "https://api.github.com/repos/dtrupenn/Tetris/git/trees{/sha}",
    // "clone_url": "https://github.com/dtrupenn/Tetris.git",
    // "mirror_url": "git:git.example.com/dtrupenn/Tetris",
    // "hooks_url": "https://api.github.com/repos/dtrupenn/Tetris/hooks",
    // "svn_url": "https://svn.github.com/dtrupenn/Tetris",
    "forks": number,
}

export interface IRepositoriesFetch {
    "total_count": number,
    "incomplete_results": boolean,
    "items": IRepository[]
}

